In [1]:
!python -m pip install psycopg2-binary apyori

You should consider upgrading via the 'C:\Users\abcis\AppData\Local\Programs\Python\Python37\python.exe -m pip install --upgrade pip' command.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import psycopg2 as pg
from apyori import apriori
%matplotlib inline
import getpass
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Classification based on keyups and keydowns

### Creation dataset

In [31]:
data = {'ID':[1, 1, 1, 2,2,2], 'UP1':[121, 103, 119, 71, 106,55], 'UP2':[200, 175, 208, 231, 197,230], 'UP3':[337, 287, 335, 447, 408,446],  'UP4':[536, 400, 455, 591, 513,558], 'UP5':[712, 544, 583, 871, 795,832], 'UP6':[872, 631, 743, 1039, 902,1007],
'DOWN1':[0, 0, 0, 0, 0, 0], 'DOWN1':[98, 81, 144, 159, 132,166], 'DOWN3':[241, 208, 248, 367, 323,368], 'DOWN4':[385, 241, 320, 519, 420,494], 'DOWN5':[624, 432, 496, 792, 696,768], 'DOWN6':[785, 570, 648, 959, 823,934]
}  

In [32]:
test = pd.DataFrame(data)  
  

### Split - train and test

In [33]:
test

ID  UP1  UP2  UP3  UP4  UP5   UP6  DOWN1  DOWN3  DOWN4  DOWN5  DOWN6
0   1  121  200  337  536  712   872     98    241    385    624    785
1   1  103  175  287  400  544   631     81    208    241    432    570
2   1  119  208  335  455  583   743    144    248    320    496    648
3   2   71  231  447  591  871  1039    159    367    519    792    959
4   2  106  197  408  513  795   902    132    323    420    696    823
5   2   55  230  446  558  832  1007    166    368    494    768    934

In [35]:
treino = test.loc[test.index %2 ==0]
print (treino)

   ID  UP1  UP2  UP3  UP4  UP5  UP6  DOWN1  DOWN3  DOWN4  DOWN5  DOWN6
0   1  121  200  337  536  712  872     98    241    385    624    785
2   1  119  208  335  455  583  743    144    248    320    496    648
4   2  106  197  408  513  795  902    132    323    420    696    823


In [36]:
pred = test.loc[test.index %2 !=0]
print (pred)

   ID  UP1  UP2  UP3  UP4  UP5   UP6  DOWN1  DOWN3  DOWN4  DOWN5  DOWN6
1   1  103  175  287  400  544   631     81    208    241    432    570
3   2   71  231  447  591  871  1039    159    367    519    792    959
5   2   55  230  446  558  832  1007    166    368    494    768    934


In [54]:
X = treino.drop(['ID'], axis=1)
y = treino[['ID']]

In [55]:
X_pred = pred.drop(['ID'], axis=1)

In [56]:
y_pred = pred[['ID']]

### KNN

In [ ]:
model = KNeighborsClassifier(n_neighbors=2)

In [57]:
model.fit(X,y)

C:\Users\abcis\.pyenv\pyenv-win\versions\3.9.0\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=2)

In [58]:
predicted = model.predict(X_pred)

C:\Users\abcis\.pyenv\pyenv-win\versions\3.9.0\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [59]:
predicted

array([1, 1, 1], dtype=int64)

#### Evaluation

In [60]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_pred, predicted))

Accuracy: 0.3333333333333333


### Random Forest

In [62]:
rfc = RandomForestClassifier()
rfc.fit(X, y)

C:\Users\abcis\AppData\Local\Temp/ipykernel_21664/3685092804.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X, y)


RandomForestClassifier()

In [64]:
pred=rfc.predict(X_pred)

In [66]:
pred

array([1, 2, 2], dtype=int64)

#### Evaluation

In [65]:
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

print(accuracy_score(y_pred, pred))
print(recall_score(y_pred, pred))
print(confusion_matrix(y_pred,pred))

1.0
1.0
[[1 0]
 [0 2]]
