In [1]:
!python -m pip install psycopg2-binary apyori

/usr/bin/python: No module named pip


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import psycopg2 as pg
from apyori import apriori
%matplotlib inline
import getpass
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Classification based on keyups and keydowns

### Creation dataset

In [3]:
data = {
    'ID':[1, 1, 1, 2,2,2,3,3,3],
    'UP1':[121, 103, 119, 71, 106,55,94,111,137,],
    'UP2':[200, 175, 208, 231, 197,230,233,274,246,],
    'UP3':[337, 287, 335, 447, 408,446,271,307,293],
    'UP4':[536, 400, 455, 591, 513,558,334,383,406,],
    'UP5':[712, 544, 583, 871, 795,832,405,427,428,],
    'UP6':[872, 631, 743, 1039, 902,1007,504,523,547],  
    'DOWN1':[0, 0, 0, 0, 0, 0, 0,0,0,],
    'DOWN2':[98, 81, 144, 159, 132,166,57,78,28],
    'DOWN3':[241, 208, 248, 367, 323,368,134,177,146],
    'DOWN4':[385, 241, 320, 519, 420,494,187,235,223],
    'DOWN5':[624, 432, 496, 792, 696,768,267,320,286],
    'DOWN6':[785, 570, 648, 959, 823,934,366,399,376],
    
} 

In [4]:
test = pd.DataFrame(data)  

### Split - train and test

In [5]:
test.head(3)

ID  UP1  UP2  UP3  UP4  UP5  UP6  DOWN1  DOWN2  DOWN3  DOWN4  DOWN5  DOWN6
0   1  121  200  337  536  712  872      0     98    241    385    624    785
1   1  103  175  287  400  544  631      0     81    208    241    432    570
2   1  119  208  335  455  583  743      0    144    248    320    496    648

In [6]:
treino = test.loc[test.index %2 ==0]
print (treino)

   ID  UP1  UP2  UP3  UP4  UP5  UP6  DOWN1  DOWN2  DOWN3  DOWN4  DOWN5  DOWN6
0   1  121  200  337  536  712  872      0     98    241    385    624    785
2   1  119  208  335  455  583  743      0    144    248    320    496    648
4   2  106  197  408  513  795  902      0    132    323    420    696    823
6   3   94  233  271  334  405  504      0     57    134    187    267    366
8   3  137  246  293  406  428  547      0     28    146    223    286    376


In [7]:
pred = test.loc[test.index %2 !=0]
print (pred)

   ID  UP1  UP2  UP3  UP4  UP5   UP6  DOWN1  DOWN2  DOWN3  DOWN4  DOWN5  DOWN6
1   1  103  175  287  400  544   631      0     81    208    241    432    570
3   2   71  231  447  591  871  1039      0    159    367    519    792    959
5   2   55  230  446  558  832  1007      0    166    368    494    768    934
7   3  111  274  307  383  427   523      0     78    177    235    320    399


In [8]:
X = treino.drop(['ID'], axis=1)
y = treino[['ID']]

In [9]:
X_pred = pred.drop(['ID'], axis=1)

In [10]:
y_pred = pred[['ID']]

### KNN

In [11]:
model = KNeighborsClassifier(n_neighbors=2)

In [12]:
model.fit(X,y)

/home/gabriel/.local/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=2)

In [13]:
predicted = model.predict(X_pred)

In [14]:
predicted

array([1, 1, 1, 3])

#### Evaluation

In [15]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_pred, predicted))

Accuracy: 0.5


### Random Forest

In [16]:
rfc = RandomForestClassifier()
rfc.fit(X, y)

/tmp/ipykernel_51851/3685092804.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X, y)


RandomForestClassifier()

In [17]:
pred=rfc.predict(X_pred)

In [18]:
pred

array([1, 2, 2, 3])

#### Evaluation

In [19]:
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

print(accuracy_score(y_pred, pred))
print(recall_score(y_pred, pred, average='macro'))
print(confusion_matrix(y_pred,pred))

1.0
1.0
[[1 0 0]
 [0 2 0]
 [0 0 1]]
